### ISSUE TITLE
Delete SAS Token from vault after expiration

### ISSUE THREAD

**Issue by bmg13** [eclipse-edc/Technology-Azure#299]
# Feature Request

This Feature Request aims at delete the SAS Token, once is no longer viable to be used in transfers, to reduce the storage of not needed entries.

## Why Is the Feature Desired?

Currently, the SAS Token is created with [a fixed timeframe](https://github.com/eclipse-edc/Technology-Azure/blob/main/extensions/control-plane/provision/provision-blob/src/main/java/org/eclipse/edc/connector/provision/azure/blob/ObjectStorageProvisioner.java#L64) after which the token cannot be used for a transfer (even if it already started).
However, after secret is stored in the respective vault, it is never deleted, even after expiration, so unusable secrets are stored indefinitably.

## Solution Proposal

Suggestion would go to delete the SAS Token after a Transfer has been processed (successfully or not). A possible approach would be to delete it during the `deprovisioning` phase ([here](https://github.com/eclipse-edc/Technology-Azure/blob/main/extensions/control-plane/provision/provision-blob/src/main/java/org/eclipse/edc/connector/provision/azure/blob/ObjectStorageProvisioner.java#L97)), however this has not yet been tested so validity cannot be confirmed.

**Comment by ndr-brt** [comment]
The delete of the secret token should be already done externally in the TransferProcess state machine by the [`DeprovisionResponseHandler`](https://github.com/eclipse-edc/Connector/blob/abdc0018c847c87e7e7b29a9ca16988199fd66a4/core/control-plane/control-plane-transfer/src/main/java/org/eclipse/edc/connector/controlplane/transfer/provision/DeprovisionResponsesHandler.java#L109)
this because this behavior should be shared in all the provisioner implementations.

If there's an issue there then I think it could be considered a bug and opened in the Connector repo.

**Comment by bmg13** [comment]
> The delete of the secret token should be already done externally in the TransferProcess state machine by the [`DeprovisionResponseHandler`](https://github.com/eclipse-edc/Connector/blob/abdc0018c847c87e7e7b29a9ca16988199fd66a4/core/control-plane/control-plane-transfer/src/main/java/org/eclipse/edc/connector/controlplane/transfer/provision/DeprovisionResponsesHandler.java#L109) this because this behavior should be shared in all the provisioner implementations.
> 
> If there's an issue there then I think it could be considered a bug and opened in the Connector repo.

What we are seeing is that the SAS Token is not being deleted from the vault, so a potential bug is happening. Will update this issue after investigating it. For now will delete and will reopen if needed. Thank you for the feedback, @ndr-brt !
